riddles = [
		("""Take one out and scratch my head, \nI am now black but once was red.\nWhat am I?""", "A match", ["A match", "A cat", "", ""]), 
		("I'm bigger than an elephant, but lighter than a feather. What am I?", "The wind", ["A flag", "The wind", "A bubble", ""]), 
		("""For some I go fast\nfor others I'm slow.\nTo most people, I'm an obsession\nrelying on me is a well practiced lesson.\nWhat am I? """, "Time", ["Math", "Life", "Time", "Shadow"]), 
		("A blue house is made of blue bricks. A yellow house is made of yellow bricks. A red house is made of red bricks. An orange house is made of orange bricks. What would a green house be made of?", "Glass", ["Green bricks", "Plants", "Wood", "Glass"]), 
		("What has roots as nobody sees. Is taller than trees. Up, up it goes. And yet never grows?", "A mountain", ["A mountain", "", "A kite", ""]), 
		("""What is it that when\nyou take away the whole,\nyou still have some left over? """, "The wholesome", ["A pie", "", "", "Wholesome"]), 
		("They have not flesh, nor feathers, nor scales, nor bone. Yet they have fingers and thumbs of their own. What are they? ", "Gloves", ["Gloves", "", "Socks", "A fork"]), 
		("""This is as light as a feather,\nYet no man can hold it for long.\nWhat is it? """, "Breath", ["Butterfly", "Breath", "A fart", "Fire"]), 
		("This old one runs forever, but never moves at all. He has not lungs nor throat, but still a mighty roaring call. What is it? ", "A waterfall", ["The wind", "", "", "A waterfall"]), 
		("No sooner spoken than broken. What is it? ", "Silence", ["", "", "Silence", "A secret"]), 
		("You hear it speak, for it has a hard tongue. But it cannot breathe, for it has not a lung. What is it? ", "A bell", ["A bell", "A clock-tower", "The truth", "Speaker"]), 
		("What is red and blue, and purple and green? No one can reach it, not even the queen? ", "A rainbow", ["Flowers", "The sunsent", "A rainbow", "Planets"]),
		("Who makes it, has no need of it. Who buys it, has no use for it. Who uses it, can neither see nor feel it.", "A coffin", ["A coffin", "Stock", "", ""]),
		("I have four wings, but cannot fly, I never laugh and never cry; On the same spot I'm always found, toiling away with little sound. What am I?", "A windmill", ["", "A windmill", "", ""]), 
		("What is yours but your friends use it more than you do?", "Your name", ["Your clothes", "Your name", "Your bathroom", "Your house"]), 
		("We are little creatures; all of us have different features. One of us in glass is set; one of us you'll find in jet. Another you may see in tin, and the fourth is boxed within. If the fifth you should pursue, it can never fly from you. What are we?", "The vowels", ["The vowels", "Tools", "", ""]), 
		("Round as a marble; blue as the sea; unless I am brown or grey maybe. Smile and I shine my window pane. Frown at me and down comes my rain. I see all things but nothing I hear. Sing me to sleep and I disappear. What am I?", "An eye", ["The moon", "Earth", "", "An eye"]), 
		("Throw me off the highest building, and I'll not break. But put me in the ocean, and I will.  What am I?", "A tissue", ["A Nokia 360", "An ice-cube", "Salt", "A tissue"]), 
		("""No height nor depth, beginning or end.\nIt's complex structure, one cannot comprehend.\nWhat is it?""", "Outerspace", ["Outerspace", "An ocean", "", ""]), 
		("We have all been there, yet we will never go there again. We all see it vividly, yet none of us see it alike.", "The past", ["School", "The past", "Childhood", ""]), 
		("""I'm easy to catch, but hard to take away\nTry not to hold me, or it's you that will pay\nI'm the great enemy of candles\nAnd to dragons an ally\nBut go long without me, and you're sure to die\nWhat am I?""", "Breath", ["Oxigen", "Breath", "", ""]), 
		("Unlike you, with food we do not deal. But, we are able to make a light meal. What are we?", "Plants", ["Plants", "Cookbook", "Easybake ovens", ""]), 
		("How many feet does a shepherd, 70 sheep and his dog have?", "2 feet", ["6 feet", "286 feet", "76 feet", "2 feet"]), 
		("If you say my name, I no longer exist. What am I?", "Silence", ["A ghost", "A lie", "Silence", ""]),  
		("Who makes it, has no need of it. Who buys it, has no use for it. Who uses it can neither see nor feel it.", "A coffin", ["A coffin", "", "", ""]), 
		("Three eyes I have, all in a row; when the red one opens, all freeze. What am I?", "Traffic light", ["Traffic light", "", "", ""]), 
		("What do you use to \"hoe a row, slay a foe, and wring with woe\"?", "Your hands", ["A sword", "A juicer", "A hoe", "Your hands"])
	]
